### ISSUE TITLE
Errors are not exported correctly to csv

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#107]
Put each error on a different line (in tabular format)

This is how it looks for me (on windows) - everything is on 1 single line;

![image](https://user-images.githubusercontent.com/29144964/100208839-d4702180-2f11-11eb-9533-68ed124873b0.png)

**Comment by denisshevchenko** [comment]
Fixed in https://github.com/input-output-hk/cardano-rt-view/pull/108
