### ISSUE TITLE
[BUILD] When building with haddock enabled, build fails

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/cardano-rt-view#111]
Folloiwing comments breaks the build if build is enabled with `haddock` using GHC 8.10.2, have not tried to replicate with `8.6.5`

https://github.com/input-output-hk/cardano-rt-view/blob/707566aaadc1cda4cd033bf866fb4ab3c0af7f6f/src/Cardano/RTView/NodeState/Updater.hs#L234-L237

Possible workarrounds:

  - Apply this patch: [remove-haddock-problematic-comment.txt](https://github.com/input-output-hk/cardano-rt-view/files/5604457/remove-haddock-problematic-comment.txt)
  - Disable `haddock` entirely e.q. using RPM macro `%ghc_lib_build_without_haddock`

**Comment by denisshevchenko** [comment]
Thanks @mark-stopka, fixed: https://github.com/input-output-hk/cardano-rt-view/commit/3d9743e81ba6af86a17cb2fb8cdc15281753c55c
