### ISSUE TITLE
Compatibility with cardano-node 1.24.2

### ISSUE THREAD

**Issue by snajjar** [input-output-hk/cardano-rt-view#120]
Hello,

As you know, cardano-node 1.24.2 is out and everyone is migrating (or has migrated).
But RTView still did not provide an officially compatible version of RTView, and LiveView has been removed.

If the current version of RTView is compatible, please add it into the script and remove the warnings.

Cheers,

**Comment by denisshevchenko** [comment]
Yes, it will be done in the coming release 0.3.0.
