### ISSUE TITLE
Relays Not Working with CNTools

### ISSUE THREAD

**Issue by RRusso84** [input-output-hk/cardano-rt-view#125]
Relay Nodes info don't display when node is running with CNTools.

**Comment by denisshevchenko** [comment]
Could you provide more information, please? Versions, your node's configuration file, RTView configuration file, etc.

**Comment by RRusso84** [comment]
Sorry about that.

On 3 nodes, (2 relays and 1 producer) Im running 1.24.2 and I installed RTView 0.3.0 on a separate server...It looks like my blockproducer is fine but no data to coming from my relays. https://prnt.sc/w791ea

Since I'm using CNTools an my immediate thought is that it's conflicting with topologyUpdater file, is this possible?

here is the bottom on my config file for one of the conflicting nodes: (yes, it's suppose to be 30001)
https://prnt.sc/w78zmf

Everything else in config file has been double checked and looks good to me.
https://prnt.sc/w7at33

**Comment by RRusso84** [comment]
Fixed it. My appologies!
