### ISSUE TITLE
Relay node: Protocol/Version/Commit are not displayed on Windows

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#13]
Steps to reproduce:
1. start rt-view
2. start relay node with the changes required by rt-view
3. continue to start the rt-view

Platform: Windows 10
Cardano-node version: 1.19.1

![image](https://user-images.githubusercontent.com/29144964/94665916-6cd49600-0315-11eb-99c3-eea68419df50.png)

**Comment by dorin100** [comment]
The Node Release/Version/Commit should be displayed also in the case the rt-view is closed (by accident) and reopen.

**Comment by denisshevchenko** [comment]
Tested with these configs: https://hydra.iohk.io/build/4290242/download/1/index.html. NixOS 20.03, node `1.20.0` - no problem, protocol, version, and commit are here.

**Comment by denisshevchenko** [comment]
Latest [build on Windows](https://hydra.iohk.io/build/4284053/download/1/cardano-rt-view-0.1.0-win64.zip) is working correctly.

**Comment by denisshevchenko** [comment]
The problem was in the node's configuration: 3 tracers for these 3 metrics should be added.
