### ISSUE TITLE
Node Name Issue

### ISSUE THREAD

**Issue by RRusso84** [input-output-hk/cardano-rt-view#133]
just an fyi...

I downloaded 0.3.0 and ran into issues with the email notification that crashed rtview...needed to rebuild...

on new rebuild, I started incorporating IP into the name (example: "Relay-1_123.34.98"); however, it still wasn't working (all nodes were idle)

I went through several rebuilds trying to troubleshoot the issue and then fixed it with changing Node name within rtView back to 
- "CoreProducer"
- "Relay-1"
- "Relay-2"

All Fixed.

**Comment by denisshevchenko** [comment]
So, do you mean that `Relay-1` works and `Relay-1_123.34.98` doesn't?

**Comment by RRusso84** [comment]
Correct.

**Comment by denisshevchenko** [comment]
@RRusso84 The problem is a dot: node's name cannot contain **dots** and/or **spaces**. So you can use `Relay-1_123_34_98` or `Relay-1_123-34-98` names instead.

Unfortunately, it cannot be fixed right now, because of limitations in `iohk-monitoring-framework` code.
