### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by ghost** [input-output-hk/cardano-rt-view#138]
Cardano node: 1.24.2
RTView: 0.3.0

Error - `cardano-rt-view: HandshakeFailed (Error_Packet_Parsing "Failed reading: invalid header type: 50\nFrom:\theader\n\n")`

SMTP server used gmail.

After adding SMTP server info my RTView would restart and the node info would go idle. I restarted the nodes but the RTView would disconnect after 1-5 mins and node info would go silent and idle.

The problem was I used SSL set to TLS.  After updating it to STARTTLS this went away and RTView is running without any issues.

Is it possible to add a test button to send a test email when adding SMTP info or just auto send a test email when info is added. 

Should smtp info change after, RTView needs to handle the error without breaking.

**Comment by denisshevchenko** [comment]
In the latest build, it is already fixed (and `Test email` button is added as well). Please read the new document: https://github.com/input-output-hk/cardano-rt-view/blob/master/doc/technical-details/email-notifications.md
