### ISSUE TITLE
Browser <-> Server communication broken when reloading the rt-view web page

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#14]
Steps to reproduce:
1. start rt-view + node
2. reload the rt-view web page --> the below message can be seen into the logs

```
cardano-rt-view.exe: Foreign.JavaScript: Browser <-> Server communication broken
```

```
127.0.0.1 - - [30/Sep/2020:12:13:00 +0300] "GET /static/images/iohk-logo.png HTTP/1.1" 200 8764 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
Foreign.JavaScript: Browser window disconnected.
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET / HTTP/1.1" 200 369 - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET / HTTP/1.1" 200 369 - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /haskell.css HTTP/1.1" 200 80 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /haskell.js HTTP/1.1" 200 100857 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /favicon.ico HTTP/1.1" 200 369 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /static/css/w3.css HTTP/1.1" 304 0 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /static/js/chart.js HTTP/1.1" 304 0 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /static/images/question-circle-solid.svg HTTP/1.1" 200 868 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
127.0.0.1 - - [30/Sep/2020:12:15:36 +0300] "GET /static/images/iohk-logo.png HTTP/1.1" 200 8764 "http://127.0.0.1:8024/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
cardano-rt-view.exe: Foreign.JavaScript: Browser <-> Server communication broken.
```

**Comment by denisshevchenko** [comment]
This is not a bug, this is the nature of websockets.

Technically, RTView UI is implemented using Haskell package [threepenny-gui](https://hackage.haskell.org/package/threepenny-gui), and this package is built upon websockets. When the user reloads web-page - websocket connection disappears of course, that why [threepenny-gui](https://hackage.haskell.org/package/threepenny-gui) package (not RTView!) shows this warning message.

**Comment by dorin100** [comment]
Just a side note - anytime I, as a user of any app, see keywords as exception, error, broken, etc in the logs of that app, I lose the confidence in the displayed values. Ideally, this possible lack of confidence should be managed in some way.  

Usually, there are different actions that could be taken in order to improve user confidence in such situations: 
- address such cases in release note - mark the bug as `known issue`, add a decent explanation and add it into the release notes
- add some code changes (when possible) in order to change the log message into something more friendly;

**Comment by alexygeorgos** [comment]
In my case the web page get refreshed automatically and the message mentioned above is printed in a loop. So i'm not able to interact with RTView at all. Is there some workaround for this issue? 
I'm using localhost on windows WSL2

**Comment by bolt12** [comment]
> In my case the web page get refreshed automatically and the message mentioned above is printed in a loop. So i'm not able to interact with RTView at all. Is there some workaround for this issue? I'm using localhost on windows WSL2

I am experiencing this issue as well. Might be relevant to mention I am on a SSH local port forwarding
