### ISSUE TITLE
The Errors csv file is not correctly open on Windows (using excel)

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#142]
OS: Windows 10
RTView version: 0.3.0

1. Download the errors as CSV
2. Open the generated CSV file - using excel or notepad++ --> everything is on 1 single line

**Comment by denisshevchenko** [comment]
I've tested it on Window 10 (64-bit, Russian version), in LibreOffice and NotePad++:

<img width="321" alt="LibreOffice" src="https://user-images.githubusercontent.com/5082435/104085727-10b1d400-526b-11eb-8010-4f3948959135.png">
<img width="321" alt="NotePad" src="https://user-images.githubusercontent.com/5082435/104085748-448cf980-526b-11eb-9172-a6fc0e06dfc9.png">

So, it works correctly: I see _many_ lines, not one _single_ line. It means that it's not a Windows-specific problem.

**Comment by denisshevchenko** [comment]
Moreover, I've tried to open it in Excel (free online version) as well:

![screenshot_2021-01-09_113520](https://user-images.githubusercontent.com/5082435/104086162-e235f800-526e-11eb-892a-43281a1dbb30.png)

I don't know what's the difference between the online version of Excel and the real desktop Excel.
