### ISSUE TITLE
starting rt-view from service fails - no way to force Y for configuration answer

### ISSUE THREAD

**Issue by mik1893** [input-output-hk/cardano-rt-view#157]
Hi,
I couldn't find anything in the documentation - if I try to setup cardano-rt-view as a service, it will fail to start as it's requesting a user input (the Y for acceptance of config file) 
Is there a flag to skip it? Or is it a missing feature?

**Comment by r-tde** [comment]
You need to run it once and generate the JSON configuration file, then you can run it with that as an argument ` --config <CONFIG FILE>`.

**Comment by mik1893** [comment]
Thanks!
