### ISSUE TITLE
Doesn't appear to render correctly w/ latest node 1.26.1 (could have been a problem before also)

### ISSUE THREAD

**Issue by bourkefloyd** [input-output-hk/cardano-rt-view#165]
<img width="882" alt="Screen Shot 2021-04-14 at 5 56 11 PM" src="https://user-images.githubusercontent.com/208535/114798673-bbde9780-9d4a-11eb-81f9-10d201d7cb61.png">

**Comment by denisshevchenko** [comment]
The reason is a wrong path to `static` dir (with static content). Please check it out: https://github.com/input-output-hk/cardano-rt-view/issues/158

**Comment by bourkefloyd** [comment]
Thanks!
