### ISSUE TITLE
Documentation - explain each displayed parameter

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#19]
As a pool operator, I am interested to find:
- Forged blocks number - as the number of blocks forged from the last restart (ideally this should be historically but I don't think they have how to get this value)
- no of slots the node was elected to create a block (won the lottery) but because multiple nodes were competing, other's node block was chosen
- no of slots my node missed (and did not try to compete in the lottery) because it was not properly synced

For the moment I cannot make an accurate correlation between the above expectations and the available values.

**Comment by denisshevchenko** [comment]
Now, every metric on the web-page (both in Pane and Grid mode) has a tooltip with a short explanation about it. Particularly:

* Forged blocks number -> `Forged blocks number`
* no of slots the node was elected to create a block -> `Slot leader, number`
* no of slots my node missed -> `Missed slots number`

Probably, SPO will want to see additional information on the web-page, it will be done in the next issues.
