### ISSUE TITLE
"Peers number" value inside the Grid View is not correct

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#20]
I have 3 relay nodes (on the same machine - synced to shelley-qa). 

OS: windows 10

![image](https://user-images.githubusercontent.com/29144964/94674916-8ed41580-0321-11eb-8b88-e540af1b9c51.png)
![image](https://user-images.githubusercontent.com/29144964/94674943-9eebf500-0321-11eb-8bfa-5f720c9c8f09.png)

**Comment by ArturWieczorek** [comment]
Same issue on Linux, "Peers number" value inside the Grid View is equal to 0 for all my nodes while in Pane View peers are being displayed.
