### ISSUE TITLE
Pipe name is truncated

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#34]
![image](https://user-images.githubusercontent.com/29144964/95329118-2059ff00-08af-11eb-9817-da3066d3d245.png)

**Comment by dorin100** [comment]
the same also in the grid view

**Comment by denisshevchenko** [comment]
Yes, it's truncated to avoid "line break", especially on small screens. For example, on macOS the default paths to the pipes are really long, so I show just N first symbols + N last symbols. If the user wants to see the full path to the pipe, he can hover truncated value and the full path will be shown in the title.
