### ISSUE TITLE
Confusing message into the Errors tab

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#35]
It is not clear that inside the Errors tab we have a table with 2 columns and the name of the second column - Error message - could be interpreted as there is an Error in displaying the errors.

Idea - maybe we can make it look more like a table with an empty first raw? ...

![image](https://user-images.githubusercontent.com/29144964/95329509-ba21ac00-08af-11eb-9404-8beb4fced512.png)

**Comment by denisshevchenko** [comment]
There's a better idea: if there's no error messages, the tab `Errors` will be disabled, and it's tooltip will display something like "there's no errors".
