### ISSUE TITLE
Many entries with Error: Switchboard's queue full, dropping log items! in the service log

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-rt-view#4]
**cardano-rt-view:**

There is a lot of error entries:

> Error: Switchboard's queue full, dropping log items!
> Error: Switchboard's queue full, dropping log items!
> Error: Switchboard's queue full, dropping log items!

which suggests that node tries to forward its metrics, but without a success.

After ~ one hour they stopped appearing. 

This is the full log file, service was running for a bit over a one hour:
[rt-view-log.txt](https://github.com/input-output-hk/cardano-rt-view/files/5292177/rt-view-log.txt)

**Platform:**
Linux Mint 19.2 (Kernel: 4.15.0-101-generic)

**cardano node:**
cardano-node 1.19.1 - linux-x86_64 - ghc-8.6
git rev 497afd7dedc5d5b9bdcdb0e3cac6a50bd9f7dd54

**config files that were used:**
_node:_ the same as in https://github.com/input-output-hk/cardano-rt-view/issues/3
_cardano-rt-view:_ default options for one node.

**Comment by dorin100** [comment]
this is reproducible also on windows 10 when trying to connect rt-view to 3 local nodes (clean state) syncing to shelley-qa testnet

**Comment by dorin100** [comment]
It seems the error messages are displayed mostly when the nodes are syncing,

**Comment by denisshevchenko** [comment]
It is fixed here: https://github.com/input-output-hk/iohk-monitoring-framework/pull/591. Corresponding PR in `cardano-node` is opened: https://github.com/input-output-hk/cardano-node/pull/1975
