### ISSUE TITLE
RTView: lack of local log

### ISSUE THREAD

**Issue by denisshevchenko** [input-output-hk/cardano-rt-view#45]
Currently, RTView doesn't produce a local log. It would be useful to have such a log, at least for debugging purposes.

**Comment by dorin100** [comment]
In rt-view 0.3.0 we have a new tab available - RTView Info; Here we have:
```
Logs directory: ...../share/cardano-rt-view-logs
```
But there is no `cardano-rt-view-logs` directory inside the share directory --> there are no logs

```
dir ..../.local/share/

```
