### ISSUE TITLE
RT-View does not communicate with nodes from different machines/IPs

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/cardano-rt-view#46]
1. have a node on a different machine/VM (from the one with RT View) - IP: x.x.x.x
2. install RT View on a different machine (Windows in my case) - IP: y.y.y.y
3. open port 3011 on node machine to be accessed by RT View
4. configure the node with the below traceForwarder:
```
  "traceForwardTo": {
    "tag": "RemoteSocket",
    "contents": [
	  "y.y.y.y",
	  "3011"
	]
  }
```
5. start RT View
6. start the node

The RT View seems to not be able to connect to the node; The Node Endpoint seems not correct to.

![image](https://user-images.githubusercontent.com/29144964/95457264-477d0300-0979-11eb-8acb-f9cfb5ab9d7f.png)

PS: I tried to manually change the remoteAddr from rt-view.yaml to the IP of the remote node (x.x.x.x) but the RT View does not start anymore

**Comment by denisshevchenko** [comment]
It is related to https://github.com/input-output-hk/cardano-rt-view/issues/42
