### ISSUE TITLE
Global accessibility of webserver

### ISSUE THREAD

**Issue by TurboEgon** [input-output-hk/cardano-rt-view#59]
The Key Features shows:
3. Web-based UI: it provides configurable sections, live charts, and interactive tooltips. **Use any browser or run RTView behind a web server like NGINX and view your nodes' state on any third-party device.**

If I understand that correctly it is possible to access the web-based UI from a third-party device like:
cardano-node (Client mashine) -> cardano-rt-view (Server mashine) <- access via Browser (tablet)

I have not yet figured out how to get this setup work as cardano-rt-view seems to listening on localhost only. Any help/docu out there?

Thank you

**Comment by mark-stopka** [comment]
If it listens on local loopback, you can configure `nginx` proxy to forward traffic from external interface to `localhost`...

**Comment by denisshevchenko** [comment]
> If I understand that correctly it is possible to access the web-based UI from a third-party device like: cardano-node (Client mashine) -> cardano-rt-view (Server mashine) <- access via Browser (tablet)

Exactly.

> I have not yet figured out how to get this setup work as cardano-rt-view seems to listening on localhost only. Any help/docu out there?

Please see this guide: https://github.com/input-output-hk/cardano-rt-view/blob/master/doc/use-cases/different-machines.md

For example, if you use NGINX, you can forward http-requests to internal `127.0.0.1:8024` (if you chose the default web port) like this (in `/etc/nginx/nginx.conf`):

```
        location / {
            proxy_pass  http://127.0.0.1:8024/;
        }
```

This screenshot is taken on my phone:

![RTView on my phone](https://i.imgur.com/QVHhWgp.jpg) 

This is precisely the model you talked about: `cardano-node` (Client mashine) -> `cardano-rt-view` (Server mashine) <- access via Browser (my phone)

**Comment by TurboEgon** [comment]
thank you for your reply.
I have tried it with apache2 reverse proxying :
 ```
<VirtualHost *:80>
    ProxyPass / http://localhost:8024
    ProxyPassReverse / http://localhost:8024
    ProxyPreserveHost on
    LogLevel debug
</VirtualHost>
```
its kinda wiking now, but the website is empty. 

html source code shows:
 ```
<!doctype html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

  <title></title>
  <link rel="stylesheet" type="text/css" href="haskell.css"/>

  <!-- See https://stackoverflow.com/a/37480521  -->
  <script>if (typeof module === 'object') {window.module = module; module = undefined;}</script>
  <script src="haskell.js"></script>
  <script>if (window.module) module = window.module;</script>

  <script type="text/javascript" charset="utf-8">
    Haskell.initFFI();
  </script>
</head>
<body>
  <noscript>Please enable JavaScript.</noscript>
</body>
</html>
 ```
so the website seems to be transfered properly. 

Also RTView log shows an established connection:
 ```
127.0.0.1 - - [17/Oct/2020:19:54:08 +0200] "GET / HTTP/1.1" 200 369 - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"  
│cardano-r 1383433            root   28u  IPv4 18568943      0t0  TCP 127.0.0.1:8024->127.0.0.1:45028 (ESTABLISHED)          
 ```

**Comment by denisshevchenko** [comment]
> but the website is empty.

Yes, it's empty at the _first moment_. Technically, RTView is using `websockets` under the hood, so in the beginning the web-client receives only this short HTML-code you pasted. But after that, it initiates a connection using `Haskell.initFFI();` and then web-client receives complete HTML-code for the real page.

**Comment by TurboEgon** [comment]
Yes I allready guessed that. But why the website remains empty?

**Comment by TurboEgon** [comment]
I had to declare also rewriting rules for the websocket protocol (and add the missing slashes after ports). My final working setup for apache2 server:
````
<VirtualHost *:80>
    ProxyPass / http://localhost:8024/
    ProxyPassReverse / http://localhost:8024/

    RewriteEngine On
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://localhost:8024/$1 [P]
</VirtualHost>
````
used modules: proxy, proxy_http and proxy_wstunnel 

Thank you for your help
