### ISSUE TITLE
[FR] Add Hide all option in Select Metric menu

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-rt-view#7]
1)  I think it would be useful to also add **Hide all** option in **Select metric** menu
2) Maybe it would be a better User XP if options: **Select all** & **Hide all** would be located at the very top of the list, instead of the bottom ?

![image](https://user-images.githubusercontent.com/2938515/94438364-50165200-019f-11eb-9a35-dae9b750da3a.png)

**Comment by denisshevchenko** [comment]
@ArturWieczorek I agree that **Select all** can be located at the very top of the list. But why do we need **Hide all** option? Do you mean the situation when the user wants to hide all metrics AND then pick only the few he needs, right?

**Comment by ArturWieczorek** [comment]
> But why do we need Hide all option? Do you mean the situation when the user wants to hide all metrics AND then pick only the few he needs, right?

@denisshevchenko yes, exactly this.
