### ISSUE TITLE
[FR] Documentation - add node config file example

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-rt-view#9]
Can we attach to documentation full config file listing or add link where there will be a node config file, (at least for **mainnet**)  with all most important tracers, mappings and traceForwardTo section already added/defined so user can only download such file and start node ? I think it will be much more convenient for end users than adding it manually.

**Comment by ArturWieczorek** [comment]
And don't forget to add info that `"TurnOnLogMetrics": true,` has to be set to true and add there any other important info.

**Comment by denisshevchenko** [comment]
It's done in this PR: https://github.com/input-output-hk/cardano-rt-view/pull/37
